# lightning.pytorch==2.6.0
seed_everything: 42
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: audiosep
      name: spectro_UNetOriginal_run
      log_model: all
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 5
        filename: "{epoch:02d}"
  fast_dev_run: false
  max_epochs: 100
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: 100
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 10
  enable_checkpointing: null
  enable_progress_bar: true
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
  enable_autolog_hparams: true
  model_registry: null
model:
  class_path: audiosep.models.SpectroUNetOriginal

data:
  class_path: audiosep.data.OriginalVoiceNoiseDatamodule
  init_args:
    train_data_dir: data/train
    test_data_dir: data/test
    batch_size: 128
    num_workers: 0
    seed: 42
optimizer: null
lr_scheduler: null
checkpoint_reference: simon-yannis/audiosep/model-qeljoiln:latest
verbose: true
weights_only: null
